nubisproject/nubis-consul

nubis/packer/autoconsul.sh, nubis/terraform/inputs.tf, nubis/terraform/main.tf
=> Cleanup work

nubis/terraform/inputs.tf, nubis/terraform/main.tf
Also, reflect the release name in the name of the instances
=> Rebuild AMIs at release 10

nubis/packer/autoconsul.sh
Simple fix to autoprovision script
=> set node name to instance id, fixes issue #9

nubis/terraform/main.tf
Renaming `security_groups` to `vpc_security_group_ids` which will fix issue #41
=> Issue 41 security group rename

.gitignore, README.md, nubis/terraform/override.tf-dist
=> Sanite override.tf file

nubis/puppet/consulate.pp, nubis/puppet/init.pp
Installs consulate via python pip
=> Install consulate python package

nubis/puppet/consul.pp, nubis/puppet/files/consul-backup
Work to get consul backups going, involves dumping json file of consul to an s3 bucket
=> Consul backups

nubis/terraform/terraform.tfvars-dist
Add `manage_iam.us-west-2` variable in `terraform.tfvars-dist` file
=> Update tfvars to include manage_iam variables

nubis/puppet/consul.pp, nubis/puppet/files/consul-asg-join, nubis/puppet/files/consul-get-or-set, nubis/puppet/files/consul-publish-registration, nubis/terraform/inputs.tf, nubis/terraform/main.tf, nubis/terraform/outputs.tf
=> Stop using a bootstrap node and discover our peers via self-inspection of our auto-scaling group.

nubis/puppet/files/consul-asg-join, nubis/puppet/files/consul-backup, nubis/puppet/files/consul-publish-registration, nubis/terraform/inputs.tf, nubis/terraform/main.tf, nubis/terraform/override.tf-dist, nubis/terraform/terraform.tfvars-dist
=> Support Environment per VPCs in one account

nubis/puppet/consul.pp, nubis/puppet/files/consul-backup, nubis/terraform/main.tf, nubis/terraform/outputs.tf
=> Enable leave_on_terminate

nubis/terraform/main.tf
=> Shrink down to t2.nano

nubis/puppet/consul.pp, nubis/puppet/datadog.pp, nubis/puppet/files/consul-datadog.yaml, nubis/puppet/init.pp
=> Enable datadog integration plugin, and ship Consul telemetry to DogStatsD

nubis/puppet/files/consul-asg-join
=> Be smart about ASG joining, and don't try and re-join with known peers

nubis/puppet/consul.pp, nubis/puppet/files/consul-server-bootstrap, nubis/puppet/files/nubis-secret
=> Hide the credstash handling to its own wrapper to hide it away

nubis/puppet/awscli.pp, nubis/puppet/consul-replicate.pp
=> Move puppet logic out of the deprecated init.pp

nubis/puppet/files/consul-backup
=> Prefix Consul backups with YYYY/MM/ prefix so they list nicer in the S3 bucket

nubis/puppet/files/consul-asg-join, nubis/terraform/main.tf
=> Adopt Hashicorp's recommended way to perform rolling upgrades with Terraform

nubis/puppet/files/consul-server-bootstrap
=> Switch over to /etc/consul/zzz-join.skip

nubis/terraform/main.tf
=> Change Terraform variable min_elb_capacity to wait_for_elb_capacity as of TF v0.6.9

nubis/Puppetfile
=> nubis-consul puppet module 1.0.5 has been released.

nubis/terraform/main.tf
=> Place our UI SSL Cert (self-signed) to credstash

nubis/puppet/files/consul-server-bootstrap, nubis/puppet/files/consul-server-join
Fixes #139 and fixes #141 and fixes #138
=> Automated Platform ACL creation

nubis/builder/AMIs, nubis/builder/project.json, nubis/puppet/files/consul-server-join
=> Publish the platform ACL into credstash at nubis/$ENV/consul/acl_token

nubis/puppet/files/consul-server-bootstrap
=> Fix for new default nubis-secret prefix handling

nubis/terraform/main.tf
=> Turns out that we just needed to add the cert_signing usage to the cert to make OpenSSL happy

nubis/puppet/consul.pp
( and small puppet warning quieting)
Fixes #151
=> Upgrade to consul 0.6.3

nubis/puppet/files/consul-server-bootstrap
=> Add nubis as a protected platform ACL prefix

nubis/puppet/files/consul-server-bootstrap
=> make KV environments/ read-only for non-platform components

nubis/puppet/consul.pp
=> Upgrade Consul to 0.6.4

nubis/puppet/consul.pp, nubis/puppet/files/consul-post-bootstrap, nubis/puppet/files/consul-server-join
=> Move post bootstrap steps in its own script so it can be invoked with an exclusive lock

nubis/puppet/files/consul-post-bootstrap
=> Default the DataDog API token from Credstash

nubis/puppet/files/consul-asg-join, nubis/puppet/files/consul-backup
=> Use bash -l to make sure we load up /etc/profile.d scripts to pick up proxy setings

nubis/terraform/inputs.tf, nubis/terraform/main.tf, nubis/terraform/multi/inputs.tf, nubis/terraform/multi/main.tf, nubis/terraform/multi/outputs.tf, nubis/terraform/outputs.tf
=> terraform fmt

nubis/terraform/multi/main.tf
=> Enable versionning for our S3 buckets

nubis/terraform/multi/main.tf
=> Add missing Environment tag

nubis/puppet/files/consul-post-bootstrap, nubis/terraform/multi/inputs.tf
( Also, use consulate to manipulate KV in a cleaner fashion )
Fixes #194
=> Update DataDog API key only if it changed

nubis/terraform/multi/inputs.tf, nubis/terraform/multi/main.tf
=> Remove aws_profile, we don't need it and don't use it anymore

nubis/puppet/consul.pp
=> Upgrade to Consul 0.7.0

nubis/Puppetfile, nubis/puppet/consul.pp, nubis/puppet/files/confd/templates/consul_exporter.tmpl, nubis/puppet/statsd_exporter.pp
=> Install and run statsd_exporter and publish Consul metrics to it

nubis/puppet/files/consul-post-bootstrap, nubis/terraform/multi/main.tf
=> Convert to unicreds for secret managment

nubis/terraform/multi/main.tf
Like SSL Keys and Certs
Use:
```
echo -n "value" | credstash put-file key /dev/stdin
```
instead
=> Fix issue with unicreds choking on key values starting with --

nubis/terraform/multi/inputs.tf, nubis/terraform/multi/main.tf
=> Inject userdata into consul

nubis/terraform/multi/main.tf
=> Make sure the public SSL cert is verifiyable

nubis/puppet/consul.pp
=> Upgrade to Consul 0.7.1

nubis/puppet/consul.pp
=> Upgrade to Consul 0.7.2

nubis/puppet/consul.pp
=> Upgrade to Consul 0.7.3

nubis/terraform/multi/main.tf
=> Add ec2:DescribeTags permission

nubis/terraform/multi/main.tf
=> Add some ASG metrics for monitoring

nubis/puppet/consul.pp
=> Upgrade to Consul v0.7.5

nubis/terraform/multi/main.tf
=> Disable EC2 detailled monitoring

nubis/puppet/files/consul-aws-join
=> When consul has no peers, handle the 'null ' case as no peers too

nubis/puppet/consul.pp
They are not backwards compatible yet, see #287
Fixes #275
=> Upgrade to Consul v0.8.3, with the new ACLs disabled

nubis/terraform/multi/inputs.tf, nubis/terraform/multi/main.tf
Allow member of the SSO SG to access our web UI
=> Add support for SSO security group

nubis/terraform/multi/main.tf
=> Replace atlas with our own module

nubis/terraform/main.tf
=> Cleanup unicreds secrets on destruction

nubis/puppet/files/consul-dns-update
=> Define variables we use before using them

nubis/files/consul-backup, nubis/terraform/inputs.tf, nubis/terraform/main.tf
=> Use a generated bucket name for backups

nubis/terraform/main.tf
=> Point image search to nubis-terraform

nubis/puppet/consul_exporter.pp, nubis/puppet/dns.pp, nubis/puppet/lifecycled.pp, nubis/puppet/statsd_exporter.pp
=> Linting nubis-ci

nubis/builder/project.json
Fixes #354, make sure #355 is merged first
=> Tag this as a platform component

nubis/terraform/main.tf
Also pin random while at it
Fixes #377
=> Pin Terraform AWS provider at 1.x
